import { Task } from "../../tasks/task.model";
import { AutoGeneratedTaskProperties } from "./auto-generated-task-properties";
import { MakePartial } from "../../../utils/types/utility-types/make-partial";


export type CreateTaskPayload = Omit<
    MakePartial<Task, "completed" | "difficulty">,
    AutoGeneratedTaskProperties
>;
