import { Task } from "../../tasks/task.model";
import { AutoGeneratedTaskProperties } from "./auto-generated-task-properties";
import { MakePartial } from "../../../utils/types/utility-types/make-partial";


export type UpdateTaskPayload = MakePartial<Omit<Task, AutoGeneratedTaskProperties>> & Pick<Task, "id">
